version: '3.6'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017
  #server:
   #build:
    #  context: ./server
    #ports:
     # - 3000:3000
  movie:
    build:
      context: ./client-master
    ports:
      - 8001:8000
